import os
import sys
import settings
import telegram
import random
import re
import twitter_
from util import press_enter
import converter


def main():
	"""Main function of the program.
	
	:return: None
	"""
	if os.name == 'nt':
		from util import download_ffmpeg
		download_ffmpeg()
	random.seed()
	cfg = settings.Settings()
	while True:
		try:
			tgclass = telegram.TGBot(cfg)
			tg = tgclass.bot
			tw = twitter_.Twitter(cfg)
			print("Bot successfully started. Do CTRL-C to stop.")
			if cfg.telegram_user_id is None:
				link_key = ""
				for i in range (0, 6):
					link_key = link_key + str(random.randint(0,9))
				print("Please send your bot the following code as a Telegram message: " + link_key)
			
			@tg.message_handler(content_types=['voice'])
			def tg_audio_handler(message):
				"""Audio handler
				
				:param message: message generated by PyTelegramBotAPI
				:return:
				"""
				if message.from_user.id == cfg.telegram_user_id:
					tgclass.send_msg("We received the voice note. Please wait a few seconds while we send it to Twitter. Please don't send me anything else until you receive a reply from me.")
					voice_info = tg.get_file(message.voice.file_id)
					downloaded_voice = tg.download_file(voice_info.file_path)
					if not os.path.exists("media"):
						os.makedirs("media")
					filename = "media/"+str(message.voice.file_id)
					duration = message.voice.duration
					with open(filename+".ogg", "wb") as file:
						file.write(downloaded_voice)
					try:
						os.remove(filename + ".mp4")
					except:
						pass
					converter.convert(filename,duration)
					try:
						tw.tweet(filename + ".mp4")
						tgclass.send_msg("Audio sent. If you were replying to a Tweet, send \"/cancel\" to exit reply mode. Tweet text is now empty.")
					except KeyError as e:
						tgclass.send_msg("Audio could not be sent. Please check that you can send DM to that user.")
					os.remove(filename + ".ogg")
					os.remove(filename + ".mp4")
			
			@tg.message_handler(func=lambda msg: True)
			def tg_message_handler(message):
				"""Text message handler

				:param message: message generated by PyTelegramBotAPI
				:return:
				"""
				if cfg.telegram_user_id is None:
					if message.text == link_key:
						cfg.telegram_user_id = message.from_user.id
						tgclass.user = message.from_user.id
						print("Bot linked to " + str(message.from_user.id) + " (" + message.from_user.first_name + ")")
						tgclass.send_msg("Bot successfully linked. You can send me voice notes and I will Tweet them as a video or send me a link to a Tweet and then the voice note and I will tweet them as a reply to the specified Tweet.\nYou can also add text to the tweet using \"/text <your text here>\". To remove the text, just send that command with no text.\nSend Direct messages with /dm <user>. @ is not needed.")
						cfg.save_settings("config.cfg")
				else:
					if message.from_user.id == cfg.telegram_user_id:
						match = re.search("https://twitter.com/[a-z|A-Z|0-9|_]+/status/[0-9]+",message.text)
						if match is not None:
							url = message.text[match.start():match.end()]
							foo, tweet_id = url.rsplit("/", 1)
							tweet_text, user = tw.set_reply(tweet_id)
							if tweet_text is not None:
								tgclass.send_msg("Now replying to: @" + user + ": " + tweet_text + "\nTo post the audio as a tweet instead of a reply, send \"/cancel\"")
							else:
								tgclass.send_msg("The tweet you sent seems to not exist.")
						else:
							if message.text == "/cancel":
								tw.set_reply(None)
								tgclass.send_msg("Now posting as a Tweet.")
							elif message.text.startswith("/text"):
								if message.text == "/text" or message.text == "/text ":
									text = ""
								else:
									text = message.text[6:]
								
								while(len(text) > 240):
									spacestext = " ".join(text.split(" ")[:-1])
									if spacestext == "":
										# if it has returned an empty string it means the word has no more spaces (safety check)
										# slice at max and go
										text = text[:239]
									else:
										text = spacestext
										#check again
								
								tw.set_text(text)
								if text == "":
									tgclass.send_msg("Text cleared.")
								else:
									tgclass.send_msg("Text set to: " + text)
							elif message.text.startswith("/dm"):
								if message.text == "/dm" or message.text == "/dm ":
									user = None
								else:
									user = message.text[4:]
									user = user.replace("@", "")
								user = tw.set_dm_user(user)
								if user is None:
									tgclass.send_msg("DM cancelled.")
								else:
									tgclass.send_msg("Sending DM to @" + user + ". Send /dm with no user to exit DM mode.")
			
			tg.polling()
			tg.stop_bot()
			print("Bot stopped. It may be because you pressed CTRL-C or because an error occurred. Press enter.")
			press_enter()
			cfg.edit_settings()
			
		except ValueError as e:
			print("Error. " + e.args)
			sys.exit()
		except KeyboardInterrupt:
			pass


if __name__ == "__main__":
	main()
